name: Bug report
description: File a bug/issue to help us improve
title: "fix: <short description>"
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out. Please check existing issues first.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I’m using the latest version of create-trpc-appx
          required: true
        - label: I’ve starred the repository to support the project ⭐
          required: false
        - label: I’m considering sponsoring the project to help maintenance 💖
          required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
      placeholder: Clear and concise description of the problem…
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide minimal steps to reproduce the issue.
      placeholder: |
        1. Run this command …
        2. See error …
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs or screenshots. Redact sensitive data.
      render: shell

  - type: input
    id: version
    attributes:
      label: CLI version
      placeholder: e.g. 0.0.2

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: e.g. 20.11.0

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
  - Windows
  - Other