blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/omar-dulaimi/create-trpc-app/discussions
    about: Please use discussions for Q&A.
  - name: Ask a question
    url: https://github.com/omar-dulaimi/create-trpc-app/discussions/new
    about: Ask questions and discuss with others