name: release

on:
  push:
    branches: [master]

permissions:
  contents: write # needed to push tags and create releases
  issues: write # needed for @semantic-release/github to open fail issues
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: |
          # Ensure generated files (e.g., CHANGELOG.md) won’t fail formatting hooks
          npx prettier --write . || true
          npx semantic-release
